# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1671, 892)
        MainWindow.setStyleSheet("/* General Settings */\n"
"QWidget {\n"
"    background-color: #121212; /* Black background */\n"
"    color: #FFFFFF; /* White text */\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"/* Label */\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"/* Line Edit */\n"
"QLineEdit {\n"
"    background-color: #1E1E1E;\n"
"    border: 2px solid #5C4BDB; /* Purple border */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #9573DB; /* Lighter purple on focus */\n"
"}\n"
"\n"
"/* Text Edit */\n"
"QTextEdit {\n"
"    background-color: #1E1E1E;\n"
"    border: 2px solid #5C4BDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #9573DB;\n"
"}\n"
"\n"
"/* CheckBox */\n"
"QCheckBox {\n"
"    spacing: 8px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    background: #1E1E1E;\n"
"    border: 2px solid #5C4BDB;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: #5C4BDB;\n"
"    border: 2px solid #9573DB;\n"
"}\n"
"\n"
"/* Radio Button */\n"
"QRadioButton {\n"
"    spacing: 8px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    background: #1E1E1E;\n"
"    border: 2px solid #5C4BDB;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background: #5C4BDB;\n"
"    border: 2px solid #9573DB;\n"
"}\n"
"\n"
"/* Tab Control */\n"
"QTabWidget::pane {\n"
"    border: 2px solid #5C4BDB;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #1E1E1E;\n"
"    border: 1px solid #5C4BDB;\n"
"    padding: 8px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    min-width: 100px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #5C4BDB;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #9573DB;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* QGraphicsView */\n"
"QGraphicsView {\n"
"    background-color: #1E1E1E;\n"
"    border: 2px solid #5C4BDB;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Tree View */\n"
"QTreeView {\n"
"    background-color: #1E1E1E;\n"
"    border: 2px solid #5C4BDB;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTreeView::item {\n"
"    background-color: #1E1E1E;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTreeView::item:hover {\n"
"    background-color: #5C4BDB;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QTreeView::item:selected {\n"
"    background-color: #9573DB;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* Scroll Bars */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: #1E1E1E;\n"
"    width: 8px;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    border: 1px solid #5C4BDB;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: #5C4BDB;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {\n"
"    background: #9573DB;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: none;\n"
"    border: none;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"/* QPushButton */\n"
"QPushButton {\n"
"    background-color: #5C4BDB; /* Purple background */\n"
"    color: #FFFFFF; /* White text */\n"
"    border: 2px solid #5C4BDB; /* Match the background color */\n"
"    border-radius: 8px; /* Rounded corners */\n"
"    padding: 8px 15px;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #9573DB; /* Lighter purple on hover */\n"
"    border: 2px solid #9573DB;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4A3B9C; /* Darker purple on press */\n"
"    border: 2px solid #4A3B9C;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #1E1E1E; /* Greyed out for disabled state */\n"
"    border: 2px solid #5C4BDB; /* Slight purple outline to maintain theme */\n"
"    color: #6C6C6C; /* Faded text color */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1651, 821))
        self.tabWidget.setObjectName("tabWidget")
        self.tabServer = QtWidgets.QWidget()
        self.tabServer.setObjectName("tabServer")
        self.pushButtonStopServer = QtWidgets.QPushButton(parent=self.tabServer)
        self.pushButtonStopServer.setGeometry(QtCore.QRect(250, 10, 101, 41))
        self.pushButtonStopServer.setObjectName("pushButtonStopServer")
        self.labelServerStatus = QtWidgets.QLabel(parent=self.tabServer)
        self.labelServerStatus.setGeometry(QtCore.QRect(18, 12, 91, 31))
        self.labelServerStatus.setObjectName("labelServerStatus")
        self.textEditServerLog = QtWidgets.QTextEdit(parent=self.tabServer)
        self.textEditServerLog.setGeometry(QtCore.QRect(10, 67, 1621, 691))
        self.textEditServerLog.setObjectName("textEditServerLog")
        self.pushButtonRunServer = QtWidgets.QPushButton(parent=self.tabServer)
        self.pushButtonRunServer.setGeometry(QtCore.QRect(130, 10, 101, 41))
        self.pushButtonRunServer.setObjectName("pushButtonRunServer")
        self.tabWidget.addTab(self.tabServer, "")
        self.tabModelTraining = QtWidgets.QWidget()
        self.tabModelTraining.setObjectName("tabModelTraining")
        self.tabWidget.addTab(self.tabModelTraining, "")
        self.tabStatistics = QtWidgets.QWidget()
        self.tabStatistics.setObjectName("tabStatistics")
        self.tabWidget.addTab(self.tabStatistics, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1671, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonStopServer.setText(_translate("MainWindow", "STOP"))
        self.labelServerStatus.setText(_translate("MainWindow", "Server: OFF"))
        self.pushButtonRunServer.setText(_translate("MainWindow", "RUN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServer), _translate("MainWindow", "Server"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabModelTraining), _translate("MainWindow", "Model Training"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatistics), _translate("MainWindow", "Statistics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
